#include "parameters.h"

void from_json(const nlohmann::json& j, parameters& t)
{
	NLOHMANN_JSON_FROM(seed);
	NLOHMANN_JSON_FROM(N);
	NLOHMANN_JSON_FROM(G);
	NLOHMANN_JSON_FROM(c1);
	NLOHMANN_JSON_FROM(c2);
	NLOHMANN_JSON_FROM(v1);
	NLOHMANN_JSON_FROM(v2);
	NLOHMANN_JSON_FROM(w1);
	NLOHMANN_JSON_FROM(w2);
	NLOHMANN_JSON_FROM(w3);
	NLOHMANN_JSON_FROM(w4);
	NLOHMANN_JSON_FROM(m);
	NLOHMANN_JSON_FROM(interactionPartners);
	NLOHMANN_JSON_FROM(mutRate);
	NLOHMANN_JSON_FROM(mutStep);
	NLOHMANN_JSON_FROM(cauchyDist);
	NLOHMANN_JSON_FROM(initS01);
	NLOHMANN_JSON_FROM(initS11);
	NLOHMANN_JSON_FROM(initR01);
	NLOHMANN_JSON_FROM(initR11);
	NLOHMANN_JSON_FROM(replicates);
	NLOHMANN_JSON_FROM(reportFreq);
	NLOHMANN_JSON_FROM(dataFileName);
	NLOHMANN_JSON_FROM(dataFileFolder);
	NLOHMANN_JSON_FROM(computeMeansInCpp);
}
